c_compiler_version:
  - 11

cxx_compiler_version:
  - 11

cuda_compiler:
  - cuda-nvcc

cuda11_compiler:
  - nvcc

sysroot_version:
  - "2.17"

cmake_version:
  - ">=3.23.1,!=3.25.0"

gtest_version:
  - ">=1.13.0"

libarrow_version:
  - "=11"

dlpack_version:
  - ">=0.5,<0.6.0a0"

librdkafka_version:
  - ">=1.9.0,<1.10.0a0"

fmt_version:
  - ">=9.1.0,<10"

spdlog_version:
  - ">=1.11.0,<1.12"

# The CTK libraries below are missing from the conda-forge::cudatoolkit package
# for CUDA 11. The "*_host_*" version specifiers correspond to `11.8` packages
# and the "*_run_*" version specifiers correspond to `11.x` packages.

cuda11_libcufile_host_version:
  - "1.4.0.31"

cuda11_libcufile_run_version:
  - ">=1.0.0.82,<=1.4.0.31"

cuda11_libcurand_host_version:
  - "=10.3.0.86"

cuda11_libcurand_run_version:
  - ">=10.2.5.43,<10.3.1"

# The CTK libraries below are needed for CUDA 12+. The "*_host_*" version
# specifiers correspond to `12.0` packages and the "*_run_*" version specifiers
# correspond to `12.x` packages.

libcufile_host_version:
  - "1.5.0.59"

libcufile_run_version:
  - ">=1.5.0.59"

libcurand_host_version:
  - "=10.3.1.50"

libcurand_run_version:
  - ">=10.3.1.50"
