name: "Fix Style"
on:
  issue_comment:
    types: [created]

jobs:
  fix-style:
    if: github.event.issue.pull_request && startsWith(github.event.comment.body, 'fix style')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: pre-commit/action@v3.0.0
      - uses: EndBug/add-and-commit@v9
        with:
          fetch: false
          message: "Style fix."
